version: '3.8'

services:
  frontend:
    build:
      context: .
      target: frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: .
      target: backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=sportspot
      - DB_PASSWORD=your_password_here
      - DB_NAME=sportspot
    depends_on:
      - db

  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=sportspot
      - MYSQL_USER=sportspot
      - MYSQL_PASSWORD=your_password_here
    volumes:
      - mysql_data:/var/lib/mysql
      - ./server/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: